notas=input("Digite as notas: ").split()
N1=float(notas[0])
N2=float(notas[1])
N3=float(notas[2])
pesos=input("Digite os respectivos pesos: ").split()
P1=float(pesos[0])
P2=float(pesos[1])
P3=float(pesos[2])
NcomP=(N1*P1)+(N2*P2)+(N3*P3)
print((NcomP)/(P1+P2+P3))