print("Digite dois números: ")
num1=float(input())
num2=float(input())
print(f"{num1} + {num2} = {num1 + num2}")
print(f"{num1} - {num2} = {num1 - num2}")
print(f"{num1} X {num2} = {num1 * num2}")
print(f"{num1} / {num2} = {num1 / num2}")